### ISSUE TITLE
shellbox项目后端api部署问题

### ISSUE THREAD

**Issue by 1097872822** [Airmole/shellbox-api-docker#1]
请问作者，该“shellbox-api-docker”是其小程序接口？但我没有看到小程序中相关调用api的php文件路径，后台代码是否开源？

**Comment by 1097872822** [comment]
另外我想请问的是“高校图书资源馆藏位置”的接口怎么实现的

**Comment by Airmole** [comment]
> 请问作者，该“shellbox-api-docker”是其小程序接口？但我没有看到小程序中相关调用api的php文件路径，后台代码是否开源？

本项目是api部署环境，后台API代码不开源，但是现已支持接口模拟数据返回。

“高校图书资源馆藏位置”由校内图书馆OPAC系统提供
